/* ---------- DEMO ACCOUNTS & ROLES DATA ----------
   Rich preset accounts representing all key actors in KrishiLoop's
   circular agriculture workflow in Punjab.
------------------------------------------------- */

export const DEMO_ACCOUNTS = [
  {
    id: "acc-farmer",
    name: "Gurpreet Singh",
    firstName: "Gurpreet",
    lastName: "Singh",
    email: "gurpreet.s@demo.krishiloop.in",
    role: "Farmer",
    badge: "Verified Farmer",
    avatarBg: "#d8b34d",
    avatarColor: "#1a2717",
    initials: "GS",
    phone: "+91 98760 12345",
    district: "Sangrur",
    village: "Dhuri",
    org: "Dhuri Progressive Farmers Collective",
    bio: "Paddy and wheat farmer cultivating 18 acres in Dhuri block. Committed to zero stubble burning through prompt mechanized baling and digital marketplace listing.",
    memberSince: "Oct 2024",
    employeeId: "KL-FAR-108",
    stats: [
      { label: "Residue listed", value: "38.5 t" },
      { label: "Active supply lots", value: "3 lots" },
      { label: "Match confirmation rate", value: "94%" },
    ],
    recentActivity: [
      { type: "green", icon: "✓", text: "Listed <b>L-101</b> (12.5 t paddy straw) at Dhuri field", time: "Today, 10:15 AM" },
      { type: "straw", icon: "📈", text: "Match proposed with <b>Sangrur Biomass Pellets</b> — score 92%", time: "Yesterday, 3:40 PM" },
      { type: "blue", icon: "🔔", text: "Collection vehicle scheduled for pickup on 28 Oct", time: "2 days ago, 9:20 AM" },
      { type: "green", icon: "✓", text: "Payment released for <b>L-096</b> (₹22,500 via direct DBT transfer)", time: "5 days ago, 4:10 PM" },
    ],
  },
  {
    id: "acc-collector",
    name: "Harpreet Singh",
    firstName: "Harpreet",
    lastName: "Singh",
    email: "harpreet.collector@demo.krishiloop.in",
    role: "Collector",
    badge: "Fleet Aggregator",
    avatarBg: "#2d6e4a",
    avatarColor: "#ffffff",
    initials: "HS",
    phone: "+91 98141 87654",
    district: "Sangrur",
    village: "Sangrur",
    org: "Malwa Bio-Logistics Fleet Ltd.",
    bio: "Operating 6 balers and 12 GPS-tracked tractors across Sangrur and Malerkotla clusters. Specialised in rapid farmgate baling, route consolidation, and processing depot delivery.",
    memberSince: "Aug 2024",
    employeeId: "KL-COL-042",
    stats: [
      { label: "Total collected", value: "142 t" },
      { label: "Active routes", value: "4 routes" },
      { label: "On-time delivery", value: "98%" },
    ],
    recentActivity: [
      { type: "green", icon: "✓", text: "Completed pickup job <b>J-201</b> (18.4 t) to Sangrur Biomass Depot", time: "Today, 11:30 AM" },
      { type: "straw", icon: "📈", text: "Optimised collection route for <b>Lehragaga cluster</b> (3 farm stops)", time: "Yesterday, 5:10 PM" },
      { type: "blue", icon: "🔔", text: "Baler unit #3 deployed to Bhawanigarh fields", time: "3 days ago, 7:45 AM" },
      { type: "green", icon: "✓", text: "Digital weighbridge slip verified at Sangrur depot", time: "4 days ago, 6:00 PM" },
    ],
  },
  {
    id: "acc-processor",
    name: "Sunil Jain",
    firstName: "Sunil",
    lastName: "Jain",
    email: "sunil.jain@sangrurbiomass.com",
    role: "Processor",
    badge: "Industrial Processor",
    avatarBg: "#1b5fa1",
    avatarColor: "#ffffff",
    initials: "SJ",
    phone: "+91 98722 54321",
    district: "Malerkotla",
    village: "Malerkotla",
    org: "Sangrur Biomass Pellets Pvt. Ltd.",
    bio: "General Manager at Sangrur Biomass facility with 120 t/day intake capacity. Producing high-calorific biofuel pellets for state thermal power stations and industrial boilers.",
    memberSince: "Jul 2024",
    employeeId: "KL-PRC-019",
    stats: [
      { label: "Plant intake", value: "245 t" },
      { label: "Open requirements", value: "80 t" },
      { label: "Pellets dispatched", value: "190 t" },
    ],
    recentActivity: [
      { type: "green", icon: "✓", text: "Recorded processor intake for <b>L-104</b> (14.2 t from Jasmeet Kaur)", time: "Today, 1:20 PM" },
      { type: "straw", icon: "📈", text: "Updated biomass intake specification: max moisture 14%", time: "Yesterday, 2:00 PM" },
      { type: "blue", icon: "🔔", text: "Dispatched 40 t pellets to Punjab State Power Corporation", time: "4 days ago, 11:00 AM" },
      { type: "green", icon: "✓", text: "Confirmed boiler fuel grade quality certification", time: "1 week ago, 10:30 AM" },
    ],
  },
  {
    id: "acc-buyer",
    name: "Rajesh Sharma",
    firstName: "Rajesh",
    lastName: "Sharma",
    email: "procurement@patialapaper.in",
    role: "Buyer",
    badge: "Commercial Offtaker",
    avatarBg: "#8f6e28",
    avatarColor: "#ffffff",
    initials: "RS",
    phone: "+91 99880 11223",
    district: "Patiala",
    village: "Patiala",
    org: "Patiala Paper Board Mill",
    bio: "Head of Sustainable Procurement at Patiala Paper Mills. Sourcing unburned paddy and wheat straw for eco-friendly packaging and corrugation boards.",
    memberSince: "Nov 2024",
    employeeId: "KL-BYR-005",
    stats: [
      { label: "Straw purchased", value: "310 t" },
      { label: "Active contracts", value: "5 units" },
      { label: "Fossil coal saved", value: "185 t" },
    ],
    recentActivity: [
      { type: "green", icon: "✓", text: "Published demand requirement <b>D-203</b> (30 t Wheat straw)", time: "Yesterday, 10:00 AM" },
      { type: "straw", icon: "📈", text: "Confirmed payment release for Lot <b>L-098</b> (₹54,000)", time: "3 days ago, 4:15 PM" },
      { type: "blue", icon: "🔔", text: "Feedstock contract renewed for 2026 rabi harvest season", time: "5 days ago, 2:30 PM" },
      { type: "green", icon: "✓", text: "Corporate ESG audit verified zero-burn supply chain origin", time: "1 week ago, 3:00 PM" },
    ],
  },
  {
    id: "acc-admin",
    name: "Amanpreet Kaur",
    firstName: "Amanpreet",
    lastName: "Kaur",
    email: "amanpreet.k@punjab-agri.gov.in",
    role: "Admin",
    badge: "System Administrator",
    avatarBg: "#20593d",
    avatarColor: "#ffffff",
    initials: "AK",
    phone: "+91 98150 99887",
    district: "Chandigarh",
    village: "Chandigarh",
    org: "Punjab Agri Circular Economy Initiative",
    bio: "State nodal officer overseeing pilot monitoring, multi-district logistics, stubble fire prevention compliance, and carbon audit reporting across Punjab.",
    memberSince: "Jun 2024",
    employeeId: "KL-ADM-001",
    stats: [
      { label: "District coverage", value: "4 districts" },
      { label: "Registered farmers", value: "148" },
      { label: "Residue diverted", value: "520 t" },
    ],
    recentActivity: [
      { type: "green", icon: "✓", text: "Generated weekly pilot traceability audit report", time: "Today, 8:45 AM" },
      { type: "straw", icon: "📈", text: "Approved collector subsidy verification for <b>Sangrur fleet</b>", time: "Yesterday, 1:15 PM" },
      { type: "blue", icon: "🔔", text: "Added Malerkotla bio-CNG depot to state supply map", time: "2 days ago, 12:00 PM" },
      { type: "green", icon: "✓", text: "Synchronised satellite fire detection sensor feed with SAC", time: "3 days ago, 9:00 AM" },
    ],
  },
];

export function findAccountByRoleOrEmail(roleOrEmail) {
  if (!roleOrEmail) return DEMO_ACCOUNTS[0];
  const found = DEMO_ACCOUNTS.find(
    a => a.email.toLowerCase() === roleOrEmail.toLowerCase() || a.role.toLowerCase() === roleOrEmail.toLowerCase()
  );
  return found || DEMO_ACCOUNTS[0];
}
