import { useEffect, useMemo, useState } from "react";
import { processors as seedProcessors, lots as seedLots, route, score, weights, matchFactors } from "./data.js";

const seed = {
  lots: seedLots.map((lot) => ({ ...lot, residue: lot.residue || "Paddy straw", location: lot.village, availableUntil: "31 Oct", price: 1800, quality: "Standard", farmerId: lot.farmer, pickupJob: null, history: [{ status: lot.status, at: "2026-10-12T09:00:00.000Z" }] })),
  processors: seedProcessors.map((p, i) => ({ ...p, accepted: ["Paddy straw", ...(i === 2 ? ["Wheat straw"] : [])], capacity: p.need, specification: "Baled or loose, dry material", location: p.district })),
  jobs: [],
  records: [],
  demands: [
    { id: "D-201", processor: "Sangrur Biomass Pellets", residue: "Paddy straw", quantity: 80, due: "2026-11-10", location: "Sangrur", price: 1900, status: "Open" },
    { id: "D-202", processor: "Malerkotla Bio-CNG Unit", residue: "Paddy straw", quantity: 45, due: "2026-11-18", location: "Malerkotla", price: 1750, status: "Open" },
    { id: "D-203", processor: "Patiala Paper Board Mill", residue: "Wheat straw", quantity: 30, due: "2026-12-02", location: "Patiala", price: 1600, status: "Open" },
  ],
};
const key = "krishiloop-project-data-v1";
const roles = ["Farmer", "Collector", "Processor", "Buyer", "Admin"];
const navigation = {
  Farmer: ["Overview", "Marketplace", "My lots", "Matching", "Impact"],
  Collector: ["Overview", "Marketplace", "Pickup jobs", "Routes", "Impact"],
  Processor: ["Overview", "Marketplace", "Demand board", "Intake", "Impact"],
  Buyer: ["Overview", "Marketplace", "Demand board", "Impact"],
  Admin: ["Overview", "Marketplace", "Demand board", "Pickup jobs", "Intake", "Impact"],
};
const icons = { Overview: "⌂", Marketplace: "⌕", "My lots": "▤", Matching: "✳", "Pickup jobs": "↗", Routes: "⌁", "Demand board": "◷", Intake: "⇩", Impact: "▥" };
const loadData = () => { try { const raw = JSON.parse(localStorage.getItem(key)); if (raw?.lots && raw?.demands) return { ...seed, ...raw }; } catch {} return seed; };
const dateLabel = (value) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("en-IN", { day: "2-digit", month: "short" }) : "Flexible";
const id = (prefix, list) => `${prefix}-${String(201 + list.length).padStart(3, "0")}`;
const kmBetween = (a = "Sangrur", b = "Sangrur") => { const places = { Sangrur: [30.24, 75.84], Dhuri: [30.37, 75.87], Sunam: [30.13, 75.8], Longowal: [30.21, 75.68], Bhawanigarh: [30.27, 76.04], Lehragaga: [29.93, 75.8], Malerkotla: [30.53, 75.88], Patiala: [30.34, 76.39], Barnala: [30.38, 75.55] }; const x = places[a] || places.Sangrur, y = places[b] || places.Sangrur; const dlat = (x[0] - y[0]) * 111, dlon = (x[1] - y[1]) * 96; return Math.max(1, Math.round(Math.hypot(dlat, dlon))); };
function Mark({ children }) { return <span className="kl-mark">{children}</span>; }
function Button({ children, onClick, secondary = false, type = "button", disabled = false }) { return <button className={secondary ? "secondary" : "primary"} onClick={onClick} type={type} disabled={disabled}>{children}</button>; }
function Metric({ label, value, hint }) { return <article className="kl-metric"><span>{label}</span><b>{value}</b><small>{hint}</small></article>; }
function Auth({ onLogin }) {
  const [role, setRole] = useState("Farmer");
  return <main className="kl-auth"><section className="kl-auth-art"><a className="kl-brand" href="#home"><Mark>↗</Mark><span>KrishiLoop<small>AGRICULTURE, IN A LOOP</small></span></a><div><div className="kl-eyebrow">A BETTER WAY TO USE EVERY HARVEST</div><h1>Good for the soil.<br/><em>Great for your future.</em></h1><p>Connect farmers, collectors, processors and buyers. Give every residue lot a visible path from field to value.</p><div className="kl-proof"><span>🌾</span><span><b>From residue to resource</b><small>A community-powered circular economy that starts after harvest.</small></span></div></div><small className="kl-art-foot">Illustrative pilot experience · Punjab, India</small></section><section className="kl-auth-column"><div className="kl-auth-form"><form className="kl-auth-card" onSubmit={e => { e.preventDefault(); onLogin(e.currentTarget.email.value, role); }}><Mark>↗</Mark><div className="kl-eyebrow">YOUR LOOP STARTS HERE</div><h2>Welcome to KrishiLoop</h2><p>Choose a demo role and enter your details.</p><label>Demo role</label><div className="kl-role-grid">{roles.map(r => <button key={r} className={role===r?"chosen":""} type="button" onClick={()=>setRole(r)}>{r}</button>)}</div><label htmlFor="login-email">Email address</label><input id="login-email" name="email" type="email" placeholder="you@example.com" required defaultValue={role.toLowerCase()+"@demo.krishiloop.in"}/><label htmlFor="login-password">Password</label><input id="login-password" name="password" type="password" placeholder="Any password for this demo" minLength="4" required defaultValue="demo1234"/><Button type="submit">Enter {role} workspace <span>→</span></Button><div className="kl-demo-note">Demo sign-in runs in this browser. It does not verify identity or connect to a live service.</div></form></div><SiteFooter onLogout={null}/></section></main>;
}
function ListingModal({ onClose, onSave }) {
  const [f, setF] = useState({ farmer: "", village: "", residue: "Paddy straw", est: "", from: "", until: "", price: "1800", quality: "Standard" });
  const change = e => setF({ ...f, [e.target.name]: e.target.value });
  return <div className="kl-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="kl-modal" onSubmit={e=>{e.preventDefault();onSave(f);}}><button className="kl-close" onClick={onClose} aria-label="Close">×</button><div className="kl-eyebrow">ADD TO THE LOOP</div><h2>List agricultural residue</h2><p>Publish a supply lot for matching and collection planning.</p><div className="kl-form-grid"><label>Farmer name<input name="farmer" value={f.farmer} onChange={change} required placeholder="e.g. Jasmeet Kaur"/></label><label>Village<input name="village" value={f.village} onChange={change} required placeholder="e.g. Dhuri"/></label><label>Residue type<select name="residue" value={f.residue} onChange={change}><option>Paddy straw</option><option>Wheat straw</option><option>Mustard stalk</option><option>Other crop residue</option></select></label><label>Estimated quantity (tonnes)<input name="est" type="number" min="0.1" step="0.1" value={f.est} onChange={change} required/></label><label>Available from<input name="from" type="date" value={f.from} onChange={change} required/></label><label>Available until<input name="until" type="date" value={f.until} onChange={change} required/></label><label>Expected price (₹ / tonne)<input name="price" type="number" min="0" value={f.price} onChange={change}/></label><label>Quality / condition<select name="quality" value={f.quality} onChange={change}><option>Standard</option><option>Dry, baled</option><option>Dry, loose</option><option>Needs inspection</option></select></label></div><div className="kl-modal-actions"><Button secondary onClick={onClose}>Cancel</Button><Button type="submit">Publish supply listing →</Button></div></form></div>;
}
function AppShell({ user, onLogout }) {
  const [data, setData] = useState(loadData);
  const [page, setPage] = useState("Overview");
  const [modal, setModal] = useState(false);
  const [toast, setToast] = useState("");
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All residue");
  const [selectedLot, setSelectedLot] = useState("");
  const [dark, setDark] = useState(false);
  const [mobile, setMobile] = useState(false);
  useEffect(()=>{ localStorage.setItem(key, JSON.stringify(data)); },[data]);
  const notify = message => { setToast(message); window.clearTimeout(window.__klToast); window.__klToast=window.setTimeout(()=>setToast(""),3000); };
  const currentLots = useMemo(()=>data.lots.filter(l=>(filter==="All residue"||l.residue===filter)&&`${l.id} ${l.farmer} ${l.village} ${l.residue}`.toLowerCase().includes(search.toLowerCase())),[data.lots,filter,search]);
  const openLots = data.lots.filter(l=>!["Collected","Processed"].includes(l.status));
  const collected = data.lots.filter(l=>["Collected","Processed"].includes(l.status));
  const totalListed = data.lots.reduce((s,l)=>s+Number(l.est||0),0);
  const totalCollected = collected.reduce((s,l)=>s+Number(l.act??l.est??0),0);
  const completedJobs = data.jobs.filter(j=>j.status==="Collected").length;
  const kpis = [
    {label:"Residue listed",value:`${totalListed.toFixed(1)} t`,hint:`${data.lots.length} recorded lots`},
    {label:"Residue collected",value:`${totalCollected.toFixed(1)} t`,hint:"Recorded actual or estimated quantity"},
    {label:"Pickup completion",value:`${data.jobs.length?Math.round(completedJobs/data.jobs.length*100):0}%`,hint:`${completedJobs} of ${data.jobs.length} pickup jobs`},
    {label:"Open supply lots",value:String(openLots.length),hint:"Available for matching"},
  ];
  const addLot = f => { const lot={id:id("L",data.lots),farmer:f.farmer,village:f.village,location:f.village,residue:f.residue,est:Number(f.est),act:null,from:dateLabel(f.from),availableFrom:f.from,availableUntil:dateLabel(f.until),price:Number(f.price),quality:f.quality,status:"Listed",farmerId:f.farmer,pickupJob:null,history:[{status:"Listed",at:new Date().toISOString()}]};setData(d=>({...d,lots:[lot,...d.lots]}));setModal(false);setPage("My lots");notify("Listing published and ready for matching."); };
  const updateLot = (lotId, status, extra={}) => setData(d=>({...d,lots:d.lots.map(l=>l.id===lotId?{...l,...extra,status,history:[...(l.history||[]),{status,at:new Date().toISOString()}]}:l)}));
  const createJob = (lotIds, collector="Demo Collector") => { const group=data.lots.filter(l=>lotIds.includes(l.id)); if(!group.length)return; const job={id:id("J",data.jobs),lotIds,collector,status:"Planned",route:group.map(l=>l.village).join(" → ")+` → ${group[0].location||"Sangrur"} processor`,distance:group.reduce((n,l)=>n+kmBetween(l.village,"Sangrur"),0),schedule:new Date().toISOString().slice(0,10)};setData(d=>({...d,jobs:[job,...d.jobs],lots:d.lots.map(l=>lotIds.includes(l.id)?{...l,status:"Collection planned",pickupJob:job.id,history:[...(l.history||[]),{status:"Collection planned",at:new Date().toISOString()}]}:l)}));notify("Collection job created. Lots are now planned for pickup."); };
  const confirmPickup = job => { const actual=window.prompt("Enter actual collected quantity in tonnes:",String(data.lots.filter(l=>job.lotIds.includes(l.id)).reduce((n,l)=>n+Number(l.est),0).toFixed(1))); if(actual===null)return;const sum=Number(actual);const lots=data.lots.filter(l=>job.lotIds.includes(l.id));setData(d=>({...d,jobs:d.jobs.map(j=>j.id===job.id?{...j,status:"Collected",actualQuantity:sum,completedAt:new Date().toISOString()}:j),lots:d.lots.map(l=>job.lotIds.includes(l.id)?{...l,status:"Collected",act:Number((sum*Number(l.est)/lots.reduce((n,x)=>n+Number(x.est),0)).toFixed(1)),history:[...(l.history||[]),{status:"Collected",at:new Date().toISOString()}]}:l)}));notify("Pickup confirmed; actual quantities are recorded."); };
  const recordIntake = lot => { if(!lot)return;const qty=window.prompt(`Processor intake quantity for ${lot.id} (tonnes):`,String(lot.act??lot.est));if(qty===null)return;setData(d=>({...d,records:[{id:id("R",d.records),lotId:lot.id,processor:user.role==="Processor"?user.email.split("@")[0]:"Demo Processor",quantity:Number(qty),category:"Biomass feedstock",at:new Date().toISOString()},...d.records],lots:d.lots.map(l=>l.id===lot.id?{...l,status:"Processed",act:Number(qty),history:[...(l.history||[]),{status:"Processed",at:new Date().toISOString()}]}:l)}));notify(`${lot.id} processor intake recorded.`); };
  const nav = navigation[user.role] || navigation.Farmer;
  const go = name => {setPage(name);setMobile(false);window.scrollTo({top:0,behavior:"smooth"});};
  const matchRows = (lot) => data.processors.map(p=>{const distance=kmBetween(lot.village,p.location);const factors={compat:p.accepted.includes(lot.residue)?1:0,distance:Math.max(0,1-distance/90),quantity:Math.min(1,Number(lot.est)/Math.max(1,p.need/8)),timing:0.85,capacity:Math.min(1,p.capacity/Math.max(Number(lot.est),1)),quality:lot.quality==="Needs inspection"?.45:.85};return {...p,distance,parts:factors,percent:Math.round(score(factors)*100)};}).filter(m=>m.parts.compat).sort((a,b)=>b.percent-a.percent);
  const allMatches=matchRows(data.lots.find(l=>l.id===selectedLot)||openLots[0]||data.lots[0]||{village:"Sangrur",residue:"Paddy straw",est:1,quality:"Standard"});
  const exportCsv = () => {const rows=[["Lot","Farmer","Village","Residue","Estimated tonnes","Actual tonnes","Available from","Status"],...currentLots.map(l=>[l.id,l.farmer,l.village,l.residue,l.est,l.act??"",l.from,l.status])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="krishiloop-lots.csv";a.click();URL.revokeObjectURL(a.href);};
  const stageLabels=["Listed","Matched","Collection planned","Collected","Processed"];
  const stageQty=stageLabels.map(s=>data.lots.filter(l=>{const idx=stageLabels.indexOf(l.status);return idx>=stageLabels.indexOf(s);}).reduce((n,l)=>n+Number(l.act??l.est),0));
  const pageTitle={Overview:"A clear view of your residue loop",Marketplace:"Supply and demand, in one place","My lots":"Residue inventory","Matching":"Explainable supply matches","Pickup jobs":"Collection jobs and handovers",Routes:"Collection planning","Demand board":"Processor and buyer requirements",Intake:"Processor intake records",Impact:"Activity and impact reporting"}[page];
  return <div className={`kl-app ${dark?"kl-dark":""}`}><aside className={`kl-side ${mobile?"open":""}`}><a href="#top" className="kl-brand"><Mark>↗</Mark><span>KrishiLoop<small>AGRICULTURE, IN A LOOP</small></span></a><div className="kl-side-label">WORKSPACE</div><nav>{nav.map(n=><button key={n} className={page===n?"active":""} onClick={()=>go(n)}><i>{icons[n]}</i>{n}{n==="My lots"&&<span>{data.lots.length}</span>}</button>)}</nav><div className="kl-demo-tag"><span>●</span> Illustrative Punjab pilot</div><div className="kl-profile"><Mark>{user.email[0].toUpperCase()}</Mark><span><b>{user.email.split("@")[0]}</b><small>{user.role} demo account</small></span></div></aside><button className="kl-mobile-menu" onClick={()=>setMobile(!mobile)}>☰</button><main id="top" className="kl-main"><header className="kl-topbar"><div className="kl-crumb">KrishiLoop <span>/</span> {page}</div><div><span className="kl-season"><i/>2026 harvest · Punjab</span><button className="kl-theme" onClick={()=>setDark(!dark)} title="Toggle theme">{dark?"☀":"☾"}</button><Mark>{user.email[0].toUpperCase()}</Mark><button className="kl-signout" onClick={onLogout} title="Sign out">↪ <span>Sign out</span></button></div></header>
    <header className="kl-heading"><div><div className="kl-eyebrow">PILOT WORKSPACE <span>·</span> DEMO DATA</div><h1>{pageTitle}</h1><p>Coordinate agricultural residue from field to processor with a traceable digital workflow.</p></div>{user.role==="Farmer"&&<Button onClick={()=>setModal(true)}>＋ List residue</Button>}</header>
    <div className="kl-banner"><span>✳</span><div><b>Demo environment</b><small>Seeded farms and activity are illustrative. Changes save in this browser and are not sent to a live service.</small></div></div>
    {page==="Overview"&&<><section className="kl-loop"><div className="kl-section-head"><span><b>Your residue loop</b><small>Activity updates as the demo workflow moves forward</small></span><span className="kl-live"><i/> Browser-saved</span></div><div className="kl-stages">{["Listed","Matched","Collection planned","Collected","Processed"].map((s,i)=><div key={s}><strong>{stageQty[i].toFixed(1)}<small> t</small></strong><span>{s}</span><i style={{width:`${Math.min(100,stageQty[i]/Math.max(stageQty[0],1)*100)}%`}}/></div>)}</div></section><section className="kl-metrics">{kpis.map(k=><Metric key={k.label} {...k}/>)}</section><div className="kl-two"><section className="kl-panel"><div className="kl-panel-title"><div><div className="kl-eyebrow">LOCAL SUPPLY & DEMAND</div><h2>Punjab pilot activity</h2></div><span className="kl-pill">Illustrative</span></div><div className="kl-bars">{["Sangrur","Patiala","Malerkotla","Barnala"].map(name=>{const supply=data.lots.filter(l=>l.village===name||name==="Sangrur").reduce((n,l)=>n+Number(l.est),0);const demand=data.demands.filter(d=>d.location===name).reduce((n,d)=>n+d.quantity,0);return <div className="kl-bar-row" key={name}><span>{name}</span><div><i style={{width:`${Math.min(100,supply/Math.max(totalListed,1)*100)}%`}}/></div><b>{supply.toFixed(0)} t</b><small>Demand {demand} t</small></div>;})}</div><div className="kl-legend"><span><i/> Listed supply</span><span><i/> Open demand</span></div></section><section className="kl-panel"><div className="kl-panel-title"><div><div className="kl-eyebrow">NEXT COLLECTION</div><h2>Route planning</h2></div><button className="kl-link" onClick={()=>go("Routes")}>View routes →</button></div><RouteGraphic lots={openLots.slice(0,4)}/><div className="kl-route-foot"><span><b>{openLots.slice(0,4).length||0} stops</b><small>Nearest Sangrur cluster</small></span><span><b>{openLots.slice(0,4).reduce((n,l)=>n+kmBetween(l.village),0)} km</b><small>Approx. road distance</small></span></div></section></div><section className="kl-section-title"><div><h2>Continue the workflow</h2><p>Open a role screen to explore the end-to-end supply chain.</p></div><button className="kl-link" onClick={()=>go("Marketplace")}>Open marketplace →</button></section><div className="kl-quick-grid">{[{n:"Marketplace",t:"Explore available lots and processor requirements",i:"⌕"},{n:user.role==="Processor"?"Demand board":"Matching",t:"Review explainable demand-side matches",i:"✳"},{n:user.role==="Processor"?"Intake":"Pickup jobs",t:"Advance lots through collection and processing",i:"↗"}].map(x=><button key={x.n} onClick={()=>go(x.n)}><span>{x.i}</span><b>{x.n}</b><small>{x.t}</small><i>→</i></button>)}</div><RecentLots lots={data.lots.slice(0,5)} onView={()=>go("My lots")}/></>}
    {page==="Marketplace"&&<><section className="kl-market-summary"><Metric label="Supply lots" value={openLots.length} hint={`${totalListed.toFixed(1)} tonnes listed`}/><Metric label="Open requirements" value={data.demands.filter(d=>d.status==="Open").length} hint={`${data.demands.filter(d=>d.status==="Open").reduce((n,d)=>n+d.quantity,0)} tonnes requested`}/><Metric label="Processor network" value={data.processors.length} hint="Demo processor profiles"/></section><div className="kl-panel kl-market-panel"><div className="kl-panel-title"><div><div className="kl-eyebrow">LOCAL NETWORK</div><h2>Residue supply lots</h2><p>Browse fictional pilot listings and compare their current status.</p></div>{user.role==="Farmer"&&<Button onClick={()=>setModal(true)}>＋ Add supply</Button>}</div><LotFilters search={search} setSearch={setSearch} filter={filter} setFilter={setFilter}/><LotCards lots={currentLots} role={user.role} onMatch={l=>{setSelectedLot(l.id);go("Matching");}} onPlan={l=>createJob([l.id])} onIntake={recordIntake}/></div><div className="kl-panel kl-demand-panel"><div className="kl-panel-title"><div><div className="kl-eyebrow">BUYER SIGNAL</div><h2>Open processor demand</h2></div><button className="kl-link" onClick={()=>go("Demand board")}>All requirements →</button></div><DemandCards demands={data.demands.filter(d=>d.status==="Open")}/></div></>}
    {page==="My lots"&&<section className="kl-panel"><div className="kl-panel-title"><div><div className="kl-eyebrow">TRACEABLE SUPPLY</div><h2>All residue lots</h2><p>Estimated and collected quantities are shown separately.</p></div><Button secondary onClick={exportCsv}>↓ Export CSV</Button></div><LotFilters search={search} setSearch={setSearch} filter={filter} setFilter={setFilter}/><LotTable lots={currentLots} onPlan={createJob} onIntake={recordIntake} role={user.role}/></section>}
    {page==="Matching"&&<><section className="kl-panel kl-match-config"><div className="kl-panel-title"><div><div className="kl-eyebrow">EXPLAINABLE SCORING</div><h2>Choose a lot to match</h2><p>Ranked using residue compatibility, distance, quantity, timing, capacity and quality.</p></div><span className="kl-pill">Configurable weighted baseline</span></div><label className="kl-select-label">Residue lot<select value={selectedLot||openLots[0]?.id||""} onChange={e=>setSelectedLot(e.target.value)}>{data.lots.map(l=><option key={l.id} value={l.id}>{l.id} · {l.farmer} · {l.residue} · {l.est} t</option>)}</select></label></section><div className="kl-match-grid">{allMatches.length?allMatches.map((m,i)=><article className="kl-match-card" key={m.id}><header><span className="kl-match-rank">0{i+1}</span><span><b>{m.name}</b><small>{m.location} · accepts {m.accepted.join(", ")}</small></span><strong>{m.percent}<small>%</small></strong></header><div className="kl-match-bar"><i style={{width:`${m.percent}%`}}/></div><div className="kl-match-factors">{Object.keys(weights).map(k=><span key={k}>{({compat:"Compatibility",distance:"Distance",quantity:"Quantity fit",timing:"Timing",capacity:"Capacity",quality:"Quality"})[k]}<b>{Math.round(m.parts[k]*100)}%</b></span>)}</div><p>Approx. {m.distance} km away · demand {m.need} t · {m.specification}</p><Button secondary onClick={()=>notify(`${m.name} was added to the review queue.`)}>Save candidate</Button></article>):<p className="kl-empty">No compatible processor matches this residue type in the demo network.</p>}</div></>}
    {page==="Pickup jobs"&&<><div className="kl-panel kl-panel-title-wrap"><div className="kl-panel-title"><div><div className="kl-eyebrow">FIELD OPERATIONS</div><h2>Collection jobs</h2><p>Collectors can confirm pickup and record actual quantity.</p></div><Button secondary onClick={()=>openLots.length&&createJob(openLots.slice(0,3).map(l=>l.id))} disabled={!openLots.length}>＋ Plan nearby cluster</Button></div></div><JobCards jobs={data.jobs} lots={data.lots} role={user.role} onPickup={confirmPickup}/>{!data.jobs.length&&<EmptyCard title="No pickup jobs yet" text="Create a collection plan from the marketplace or plan the first nearby cluster." action="Open marketplace" onClick={()=>go("Marketplace")}/>}</>}
    {page==="Routes"&&<div className="kl-two kl-route-page"><section className="kl-panel"><div className="kl-panel-title"><div><div className="kl-eyebrow">SUGGESTED COLLECTION</div><h2>Nearby pickup cluster</h2></div><span className="kl-pill">Heuristic route</span></div><RouteGraphic lots={openLots.slice(0,6)}/><p className="kl-note">Route is an illustrative straight-line ordering estimate, not live navigation. Confirm road access and pickup windows with participants.</p><Button onClick={()=>openLots.length&&createJob(openLots.slice(0,3).map(l=>l.id))} disabled={!openLots.length}>Create this pickup job →</Button></section><section className="kl-panel"><div className="kl-eyebrow">PICKUP STOPS</div><h2>Lots ready to plan</h2><div className="kl-stop-list">{openLots.slice(0,8).map((l,i)=><div key={l.id}><span>{i+1}</span><div><b>{l.village}</b><small>{l.id} · {l.farmer}</small></div><strong>{l.est} t</strong></div>)}</div></section></div>}
    {page==="Demand board"&&<><div className="kl-panel kl-panel-title-wrap"><div className="kl-panel-title"><div><div className="kl-eyebrow">DEMAND VISIBILITY</div><h2>Processor requirements</h2><p>Demand figures are fictional pilot examples for demonstrating the workflow.</p></div><Button onClick={()=>{const processor=window.prompt("Processor / buyer name:","New biomass buyer");if(!processor)return;const residue=window.prompt("Residue type:","Paddy straw");if(!residue)return;const quantity=Number(window.prompt("Required quantity (tonnes):","20"));if(!quantity)return;const location=window.prompt("District / location:","Sangrur");setData(d=>({...d,demands:[{id:id("D",d.demands),processor,residue,quantity,due:"2026-11-30",location:location||"Sangrur",price:1800,status:"Open"},...d.demands]}));notify("Demand requirement published.");}}>＋ Post requirement</Button></div></div><DemandCards demands={data.demands} onClose={d=>{setData(s=>({...s,demands:s.demands.map(x=>x.id===d.id?{...x,status:"Closed"}:x)}));notify("Requirement marked closed.");}} showActions={true}/></>}
    {page==="Intake"&&<><div className="kl-panel kl-panel-title-wrap"><div className="kl-panel-title"><div><div className="kl-eyebrow">PROCESSOR OPERATIONS</div><h2>Record processor intake</h2><p>Record the actual intake quantity and close the traceability loop.</p></div></div></div><section className="kl-panel"><LotTable lots={data.lots.filter(l=>l.status==="Collected"||l.status==="Processed")} role={user.role} onIntake={recordIntake}/></section><div className="kl-panel kl-records"><div className="kl-eyebrow">INTAKE HISTORY</div><h2>Processing records</h2>{data.records.length?<div className="kl-stop-list">{data.records.map(r=><div key={r.id}><span>✓</span><div><b>{r.lotId} · {r.processor}</b><small>{r.category} · {dateLabel(r.at.slice(0,10))}</small></div><strong>{r.quantity} t</strong></div>)}</div>:<EmptyCard title="No intake records" text="When a collected lot arrives, record its processor intake here."/>}</div></>}
    {page==="Impact"&&<><section className="kl-metrics">{kpis.map(k=><Metric key={k.label} {...k}/>)}</section><div className="kl-two"><section className="kl-panel"><div className="kl-eyebrow">MEASURED FROM DEMO RECORDS</div><h2>Traceability coverage</h2><p className="kl-body">Lots with at least one recorded lifecycle event: <b>{data.lots.length?Math.round(data.lots.filter(l=>(l.history||[]).length>0).length/data.lots.length*100):0}%</b></p><div className="kl-impact-meter"><i style={{width:`${data.lots.length?data.lots.filter(l=>(l.history||[]).length>0).length/data.lots.length*100:0}%`}}/></div><p className="kl-note">This is a prototype activity indicator. It does not verify environmental benefit or avoided emissions.</p></section><section className="kl-panel"><div className="kl-eyebrow">OUTCOME RECORDS</div><h2>Verified workflow activity</h2><div className="kl-outcomes"><span><b>{data.jobs.filter(j=>j.status==="Collected").length}</b><small>Completed pickups</small></span><span><b>{data.records.length}</b><small>Processor intakes</small></span><span><b>{data.lots.filter(l=>l.status==="Processed").length}</b><small>Processed lots</small></span></div></section></div><section className="kl-panel kl-claims"><h2>Environmental indicators</h2><p>Carbon or emissions impacts are not calculated in this MVP. The report recommends adding them only when a verified methodology and eligible activity data are available.</p></section></>}
    <SiteFooter onLogout={onLogout} onNavigate={go}/></main>{toast&&<div className="kl-toast" role="status">✓ &nbsp;{toast}</div>}{modal&&<ListingModal onClose={()=>setModal(false)} onSave={addLot}/>}</div>;
}
function RouteGraphic({lots}) { const places=lots.length?lots:[{id:"A",village:"Sangrur",est:0}];return <div className="kl-route-map"><svg viewBox="0 0 520 230" role="img" aria-label="Illustrative residue pickup route map"><defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" fill="none" stroke="currentColor" strokeOpacity=".055" strokeWidth="1"/></pattern></defs><rect width="520" height="230" fill="url(#grid)"/><path d="M20 188 C98 160 82 99 162 125 S247 63 302 94 S380 147 490 49" fill="none" stroke="#dce8d7" strokeWidth="15" strokeLinecap="round"/><path d="M20 188 C98 160 82 99 162 125 S247 63 302 94 S380 147 490 49" fill="none" stroke="#7ca787" strokeWidth="2.5" strokeDasharray="5 5"/>{places.slice(0,6).map((l,i)=>{const xy=[[70,166],[150,115],[224,132],[292,81],[365,120],[440,75]][i];return <g key={l.id}><circle cx={xy[0]} cy={xy[1]} r="15" fill="#fff" stroke="#61936e" strokeWidth="2"/><text x={xy[0]} y={xy[1]+4} textAnchor="middle" fontSize="10" fill="#315c3c">{i+1}</text><text x={xy[0]} y={xy[1]+29} textAnchor="middle">{l.village}</text></g>;})}<path d="M475 37h22v22h-22z" fill="#285f40"/><path d="M480 48h12m-6-6v12" stroke="#fff" strokeWidth="2"/><text x="485" y="72" textAnchor="middle">Processor</text></svg><div className="kl-map-caption">Illustrative route ordering · approximate distances</div></div>; }
function LotFilters({search,setSearch,filter,setFilter}) { return <div className="kl-tools"><input aria-label="Search lots" placeholder="Search by farmer, village or lot ID" value={search} onChange={e=>setSearch(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All residue</option>{["Paddy straw","Wheat straw","Mustard stalk","Other crop residue"].map(x=><option key={x}>{x}</option>)}</select></div>; }
function LotCards({lots,role,onMatch,onPlan,onIntake}) { if(!lots.length)return <p className="kl-empty">No matching supply lots. Try another filter or create a listing.</p>;return <div className="kl-lot-grid">{lots.map(l=><article className="kl-lot-card" key={l.id}><header><Mark>⌁</Mark><span className={`kl-status ${l.status.replaceAll(" ","-")}`}>{l.status}</span></header><div className="kl-lot-type">{l.residue}</div><h3>{l.est} <small>tonnes estimated</small></h3><div className="kl-lot-meta"><span>⌖ {l.village}, Punjab</span><span>◷ {l.from}{l.availableUntil?` – ${l.availableUntil}`:""}</span><span>♧ {l.farmer}</span><span>₹ {Number(l.price||0).toLocaleString("en-IN")} / tonne · {l.quality}</span></div><div className="kl-card-actions">{role==="Farmer"||role==="Processor"||role==="Admin"?<Button secondary onClick={()=>onMatch(l)}>View matches</Button>:null}{["Collector","Admin"].includes(role)&&!["Collected","Processed"].includes(l.status)&&<Button onClick={()=>onPlan(l)}>Plan pickup</Button>}{["Processor","Admin"].includes(role)&&l.status==="Collected"&&<Button onClick={()=>onIntake(l)}>Record intake</Button>}</div></article>)}</div>; }
function LotTable({lots,onPlan,onIntake,role}) {return <div className="kl-table-scroll"><table className="kl-table"><thead><tr><th>LOT / SUPPLY</th><th>FARMER</th><th>LOCATION</th><th>ESTIMATED</th><th>ACTUAL PICKUP</th><th>AVAILABLE</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{lots.map(l=><tr key={l.id}><td><b>{l.id}</b><small>{l.residue}</small></td><td>{l.farmer}</td><td>{l.village}, Punjab</td><td>{l.est} t</td><td>{l.act==null?<span className="kl-muted">Pending</span>:`${l.act} t`}</td><td>{l.from}</td><td><span className={`kl-status ${l.status.replaceAll(" ","-")}`}>{l.status}</span></td><td>{["Collector","Admin"].includes(role)&&!["Collected","Processed"].includes(l.status)&&<button className="kl-row-action" onClick={()=>onPlan([l.id])}>Plan pickup</button>}{["Processor","Admin"].includes(role)&&l.status==="Collected"&&<button className="kl-row-action" onClick={()=>onIntake(l)}>Record intake</button>}</td></tr>)}</tbody></table>{!lots.length&&<p className="kl-empty">No lots to display.</p>}</div>;}
function DemandCards({demands,onClose,showActions=false}) {return demands.length?<div className="kl-demand-grid">{demands.map(d=><article key={d.id} className="kl-demand-card"><header><span className="kl-demand-icon">◷</span><span className={`kl-status ${d.status}`}>{d.status}</span></header><h3>{d.processor}</h3><p>{d.residue} · {d.location}</p><div className="kl-demand-stats"><span><b>{d.quantity} t</b><small>Required volume</small></span><span><b>{dateLabel(d.due)}</b><small>Target date</small></span><span><b>₹{Number(d.price).toLocaleString("en-IN")}</b><small>Indicative / tonne</small></span></div>{showActions&&d.status==="Open"&&<button className="kl-row-action" onClick={()=>onClose?.(d)}>Mark requirement closed</button>}</article>)}</div>:<p className="kl-empty">There are no open requirements in this demo yet.</p>;}
function JobCards({jobs,lots,role,onPickup}) {return jobs.length?<div className="kl-job-grid">{jobs.map(j=>{const group=lots.filter(l=>j.lotIds.includes(l.id));return <article className="kl-panel kl-job" key={j.id}><header><span className="kl-job-id">{j.id}</span><span className={`kl-status ${j.status}`}>{j.status}</span></header><h3>{j.route}</h3><p>{group.map(l=>l.id).join(" · ")} · {group.reduce((n,l)=>n+l.est,0).toFixed(1)} t estimated</p><div className="kl-job-info"><span>Collector<b>{j.collector}</b></span><span>Suggested distance<b>~{j.distance} km</b></span><span>Scheduled<b>{dateLabel(j.schedule)}</b></span></div>{j.status!=="Collected"&&["Collector","Admin"].includes(role)&&<Button onClick={()=>onPickup(j)}>Confirm pickup & actual quantity</Button>}{j.status==="Collected"&&<p className="kl-success">✓ Pickup confirmed · {j.actualQuantity} t actual total</p>}</article>;})}</div>:null;}
function RecentLots({lots,onView}) {return <section className="kl-panel kl-recent"><div className="kl-panel-title"><div><div className="kl-eyebrow">RECENTLY UPDATED</div><h2>Residue lots</h2></div><button className="kl-link" onClick={onView}>View inventory →</button></div><div className="kl-table-scroll"><table className="kl-table"><thead><tr><th>LOT</th><th>FARMER</th><th>VILLAGE</th><th>QUANTITY</th><th>STATUS</th></tr></thead><tbody>{lots.map(l=><tr key={l.id}><td><b>{l.id}</b></td><td>{l.farmer}</td><td>{l.village}</td><td>{l.est} t</td><td><span className={`kl-status ${l.status.replaceAll(" ","-")}`}>{l.status}</span></td></tr>)}</tbody></table></div></section>;}
function EmptyCard({title,text,action,onClick}) {return <div className="kl-empty-card"><span>↗</span><b>{title}</b><p>{text}</p>{action&&<button className="kl-link" onClick={onClick}>{action} →</button>}</div>;}
function SiteFooter({onLogout,onNavigate}) {const navTo=name=>onNavigate?onNavigate(name):document.getElementById("login-email")?.focus();return <footer className="kl-footer"><button className="kl-footer-top" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}>↑ &nbsp;Back to top</button><div className="kl-footer-main"><div className="kl-footer-groups"><section><h3>Get to know KrishiLoop</h3><button onClick={()=>navTo("Overview")}>About the project</button><button onClick={()=>navTo("Impact")}>Our impact approach</button><button onClick={()=>navTo("Marketplace")}>Punjab pilot</button><button onClick={()=>navTo("Overview")}>How the residue loop works</button></section><section><h3>Join the residue network</h3><button onClick={()=>navTo("Marketplace")}>List and discover residue</button><button onClick={()=>navTo("Demand board")}>Post processor demand</button><button onClick={()=>navTo("Pickup jobs")}>Coordinate collection</button><button onClick={()=>navTo("Matching")}>Explore smart matching</button></section><section><h3>For partners</h3><button onClick={()=>navTo("Routes")}>Collectors and aggregators</button><button onClick={()=>navTo("Intake")}>Processors and buyers</button><button onClick={()=>navTo("Demand board")}>Ecosystem organizations</button><button onClick={()=>navTo("Impact")}>Pilot activity reports</button></section><section><h3>Let us help you</h3><button onClick={()=>window.alert("This is a demo workspace. Contact and account services are not connected yet.")}>Account and access</button><button onClick={()=>window.alert("For this prototype, ask your KrishiLoop pilot coordinator for help.")}>Help & support</button><button onClick={()=>window.alert("Demo listings and activity are stored in this browser only.")}>Data and privacy</button>{onLogout&&<button onClick={onLogout}>Sign out</button>}</section></div><div className="kl-footer-bottom"><a href="#top" className="kl-footer-brand"><Mark>↗</Mark><span><b>KrishiLoop</b><small>Residue to value</small></span></a><span className="kl-footer-region">🌾 &nbsp;Punjab, India <i/> Illustrative pilot prototype</span><span className="kl-footer-copy">© 2026 KrishiLoop · Turning residue into a resource</span></div></div></footer>;}
export default function App() { const [session,setSession]=useState(()=>{try{return JSON.parse(localStorage.getItem("krishiloop-session"));}catch{return null;}});const login=(email,role)=>{const value={email,role};localStorage.setItem("krishiloop-session",JSON.stringify(value));setSession(value);};const logout=()=>{localStorage.removeItem("krishiloop-session");setSession(null);};return session?<AppShell user={session} onLogout={logout}/>:<Auth onLogin={login}/>; }
